---
title: "model"
author: "Irving, Chuy"
date: "2025-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(caret)
library(ggplot2)
library(gridExtra)
```

```{r load_data, echo=FALSE}

# Cargar datos balanceados
data_balanceada <- read.csv("../defunciones_balanceadas.csv")

```

```{r processing_data, echo=FALSE}


# Partición estratificada
set.seed(123)
train_index <- createDataPartition(data_balanceada$causa_macro, p = 0.7, list = FALSE)

train_set <- data_balanceada[train_index, ]
test_set  <- data_balanceada[-train_index, ]

prop.table(table(train_set$causa_macro))
prop.table(table(test_set$causa_macro))

train_set

# Eliminar variables específicas
vars_to_remove <- c("Añoreg", "Depreg", "Mesreg", "Mredif", "Mnadif", "Perdif", "letra_inicial","Caudef")

train_set_clean <- train_set %>% 
  select(-all_of(vars_to_remove))

test_set_clean <- test_set %>% 
  select(-all_of(vars_to_remove))

# Verificación
names(train_set_clean)

train_set_clean


```

```{r look_atipical_data_categorical, echo=FALSE}


# Variables categóricas (basado en tu metadata)
cat_vars <- c("Asist", "Depocu", "Dnadif", "Dredif", "Ecidif", "Ocur", "Sexo", "Escodif")

# Función para graficar frecuencias de categorías
plot_category_freq <- function(var) {
  train_set_clean %>% 
    count(!!sym(var)) %>% 
    ggplot(aes(x = factor(!!sym(var)), y = n)) +
    geom_bar(stat = "identity") +
    labs(title = paste("Frecuencia de categorías -", var), 
         x = var, y = "Conteo") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}

# Graficar todas las variables categóricas
walk(cat_vars, ~print(plot_category_freq(.x)))

```

```{r look_atipical_data_categorical, echo=FALSE}
num_vars <- c("Diaocu", "Edadif", "Mesocu", "year")

# Boxplots para detectar outliers numéricos
ggplot(stack(train_set_clean[num_vars]), aes(x = ind, y = values)) +
  geom_boxplot() +
  facet_wrap(~ind, scales = "free") +
  labs(title = "Distribución de variables numéricas") +
  theme_minimal()

```
```{r handle_outliers, echo=FALSE}
edad_anomalas <- sum(train_set_clean$Edadif == 999, na.rm = TRUE)
total_registros <- nrow(train_set_clean)

cat("Registros con Edadif en train = 999:", edad_anomalas, 
    "\nPorcentaje del total:", round(edad_anomalas / total_registros * 100, 2), "%")

edad_anomalas <- sum(test_set_clean$Edadif == 999, na.rm = TRUE)
total_registros <- nrow(test_set_clean)

cat("Registros con Edadif en test = 999:", edad_anomalas, 
    "\nPorcentaje del total:", round(edad_anomalas / total_registros * 100, 2), "%")

train_set_clean <- train_set_clean %>% 
  filter(Edadif != 999)

test_set_clean <- test_set %>% 
  filter(Edadif != 999) %>% 
  select(-all_of(vars_to_remove))
```

```{r handle_na, echo=FALSE}
colSums(is.na(train_set_clean))
colSums(is.na(test_set_clean))

# Imputar NA en Escodif con 9 ("Ignorado")
train_set_clean <- train_set_clean %>% 
  mutate(Escodif = ifelse(is.na(Escodif), 9, Escodif))

test_set_clean <- test_set_clean %>% 
  mutate(Escodif = ifelse(is.na(Escodif), 9, Escodif))

# ver que no queden NA
colSums(is.na(train_set_clean))
colSums(is.na(test_set_clean))

```

